apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nammit
  labels:
    app: nammit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nammit
  template:
    metadata:
      labels:
        app: nammit
    spec:
      containers:
        - name: nammit
          image: palnabarun/nammit
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nammit
  namespace: nbshelf
spec:
  selector:
    app: nammit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nammit
  namespace: nbshelf
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: nammit.nbshelf.clusters.nabarun.in
    http:
      paths:
      - backend:
          serviceName: nammit
          servicePort: 5000
        path: /
